[build]
    base = ""                  # Leave empty if your source code is in the root directory
    publish = ""

[functions]
    directory = "netlify-functions"  # Directory for Netlify serverless functions

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/api"
    status = 200
    force = true
